// Mocks generated by Mockito 5.4.6 from annotations
// in happy_notes/test/controllers/new_note_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:happy_notes/entities/note.dart' as _i5;
import 'package:happy_notes/models/notes_result.dart' as _i2;
import 'package:happy_notes/providers/notes_provider.dart' as _i4;
import 'package:happy_notes/utils/operation_result.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotesResult_0 extends _i1.SmartFake implements _i2.NotesResult {
  _FakeNotesResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOperationResult_1<T> extends _i1.SmartFake
    implements _i3.OperationResult<T> {
  _FakeOperationResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesProvider extends _i1.Mock implements _i4.NotesProvider {
  MockNotesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoadingAdd => (super.noSuchMethod(
        Invocation.getter(#isLoadingAdd),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingList => (super.noSuchMethod(
        Invocation.getter(#isLoadingList),
        returnValue: false,
      ) as bool);

  @override
  List<_i5.Note> get notes => (super.noSuchMethod(
        Invocation.getter(#notes),
        returnValue: <_i5.Note>[],
      ) as List<_i5.Note>);

  @override
  int get currentPage => (super.noSuchMethod(
        Invocation.getter(#currentPage),
        returnValue: 0,
      ) as int);

  @override
  int get totalPages => (super.noSuchMethod(
        Invocation.getter(#totalPages),
        returnValue: 0,
      ) as int);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  Map<String, List<_i5.Note>> get groupedNotes => (super.noSuchMethod(
        Invocation.getter(#groupedNotes),
        returnValue: <String, List<_i5.Note>>{},
      ) as Map<String, List<_i5.Note>>);

  @override
  bool get isAuthStateInitialized => (super.noSuchMethod(
        Invocation.getter(#isAuthStateInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i2.NotesResult> fetchNotes(
    int? pageSize,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNotes,
          [
            pageSize,
            pageNumber,
          ],
        ),
        returnValue: _i6.Future<_i2.NotesResult>.value(_FakeNotesResult_0(
          this,
          Invocation.method(
            #fetchNotes,
            [
              pageSize,
              pageNumber,
            ],
          ),
        )),
      ) as _i6.Future<_i2.NotesResult>);

  @override
  _i6.Future<void> performDelete(int? noteId) => (super.noSuchMethod(
        Invocation.method(
          #performDelete,
          [noteId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadPage(int? pageNumber) => (super.noSuchMethod(
        Invocation.method(
          #loadPage,
          [pageNumber],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> fetchNotesLegacy() => (super.noSuchMethod(
        Invocation.method(
          #fetchNotesLegacy,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refreshCurrentPage() => (super.noSuchMethod(
        Invocation.method(
          #refreshCurrentPage,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refreshNotes() => (super.noSuchMethod(
        Invocation.method(
          #refreshNotes,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.Note?> addNote(
    String? content, {
    bool? isPrivate = false,
    bool? isMarkdown = false,
    String? publishDateTime = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNote,
          [content],
          {
            #isPrivate: isPrivate,
            #isMarkdown: isMarkdown,
            #publishDateTime: publishDateTime,
          },
        ),
        returnValue: _i6.Future<_i5.Note?>.value(),
      ) as _i6.Future<_i5.Note?>);

  @override
  _i6.Future<bool> updateNote(
    int? noteId,
    String? content, {
    bool? isPrivate,
    bool? isMarkdown,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [
            noteId,
            content,
          ],
          {
            #isPrivate: isPrivate,
            #isMarkdown: isMarkdown,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i5.Note?> updateNoteAndReturn(
    int? noteId,
    String? content, {
    bool? isPrivate,
    bool? isMarkdown,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNoteAndReturn,
          [
            noteId,
            content,
          ],
          {
            #isPrivate: isPrivate,
            #isMarkdown: isMarkdown,
          },
        ),
        returnValue: _i6.Future<_i5.Note?>.value(),
      ) as _i6.Future<_i5.Note?>);

  @override
  _i6.Future<bool> undeleteNote(int? noteId) => (super.noSuchMethod(
        Invocation.method(
          #undeleteNote,
          [noteId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i5.Note?> getNote(
    int? noteId, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNote,
          [noteId],
          {#includeDeleted: includeDeleted},
        ),
        returnValue: _i6.Future<_i5.Note?>.value(),
      ) as _i6.Future<_i5.Note?>);

  @override
  _i6.Future<void> searchNotes(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchNotes,
          [query],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> fetchTagNotes(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #fetchTagNotes,
          [tag],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearAllData() => super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> onLogin() => (super.noSuchMethod(
        Invocation.method(
          #onLogin,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> navigateToPage(int? pageNumber) => (super.noSuchMethod(
        Invocation.method(
          #navigateToPage,
          [pageNumber],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.OperationResult<void>> deleteNote(int? noteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [noteId],
        ),
        returnValue: _i6.Future<_i3.OperationResult<void>>.value(
            _FakeOperationResult_1<void>(
          this,
          Invocation.method(
            #deleteNote,
            [noteId],
          ),
        )),
      ) as _i6.Future<_i3.OperationResult<void>>);

  @override
  _i6.Future<void> loadInitialData() => (super.noSuchMethod(
        Invocation.method(
          #loadInitialData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> onLogout() => (super.noSuchMethod(
        Invocation.method(
          #onLogout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> onAuthStateChanged(bool? isAuthenticated) =>
      (super.noSuchMethod(
        Invocation.method(
          #onAuthStateChanged,
          [isAuthenticated],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void resetAuthState() => super.noSuchMethod(
        Invocation.method(
          #resetAuthState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String handleServiceError(
    dynamic error,
    String? operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleServiceError,
          [
            error,
            operation,
          ],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #handleServiceError,
            [
              error,
              operation,
            ],
          ),
        ),
      ) as String);

  @override
  _i6.Future<T?> executeWithErrorHandling<T>({
    required _i6.Future<T> Function()? operation,
    required void Function(bool)? setLoading,
    required void Function(String?)? setError,
    required String? operationName,
    void Function()? onSuccess,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeWithErrorHandling,
          [],
          {
            #operation: operation,
            #setLoading: setLoading,
            #setError: setError,
            #operationName: operationName,
            #onSuccess: onSuccess,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
