// Mocks generated by Mockito 5.4.6 from annotations
// in happy_notes/test/services/fanfou_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:happy_notes/entities/fanfou_user_account.dart' as _i4;
import 'package:happy_notes/services/fanfou_user_account_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FanfouUserAccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFanfouUserAccountService extends _i1.Mock
    implements _i2.FanfouUserAccountService {
  MockFanfouUserAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FanfouUserAccount>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i3.Future<List<_i4.FanfouUserAccount>>.value(
            <_i4.FanfouUserAccount>[]),
      ) as _i3.Future<List<_i4.FanfouUserAccount>>);

  @override
  _i3.Future<String> requestToken() => (super.noSuchMethod(
        Invocation.method(
          #requestToken,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #requestToken,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> nextSyncType() => (super.noSuchMethod(
        Invocation.method(
          #nextSyncType,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> activate() => (super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> disable() => (super.noSuchMethod(
        Invocation.method(
          #disable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
