name: Build Android Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.x'
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Decode keystore file
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/key.jks

      - name: Create key.properties
        run: |
          echo "storeFile=../key.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          cat android/key.properties

      - name: Fetch Git Commit Hash
        id: get_commit
        run: |
          echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
          echo "::set-output name=build_date::$(date '+%Y-%b-%d')"

      - name: Build APK
        run: |
          cp .env.production .env
          COMMIT_HASH=${{ steps.get_commit.outputs.commit_hash }}
          BUILD_DATE=${{ steps.get_commit.outputs.build_date }}
          VERSION_INFO="$COMMIT_HASH ($BUILD_DATE)"
          sed -i "s/VERSION_PLACEHOLDER/$VERSION_INFO/" .env
          flutter build apk --release

      - name: Make Github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
